name: CI/CD Pipeline for Nginx

on:
  push:
    paths:
      - 'nginx/index.html'
  pull_request:
    paths:
      - 'nginx/index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          cd nginx
          docker build -t mynginx .

      # Step 4: Set up Docker Compose to deploy
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
