name: CI/CD Pipeline for Nginx

on:
  push:
    paths:
      - 'nginx/index.html'
  pull_request:
    paths:
      - 'nginx/index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          cd nginx
          docker build -t mynginx .

      # Step 5: Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f nginx/docker-compose.yml up -d --build

